version: '3'
services:
  libretv:
    image: bradleylzh/libretv:latest
    container_name: libretv
    ports:
      - "8899:80"
    environment:
      - PASSWORD=kkdy123456
      - DANMAKU_API_URL=http://152.136.12.42:5005
    restart: unless-stopped